### ISSUE TITLE
stuck in expedition only mode

### ISSUE THREAD

**Issue by riseri** [EchoControl/Gunkolle#1]
**Desktop:**
What graphics card are you using? 2070

**Config File:**
[Do Not Modify]
Busy=0

[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=M4SOPMODII
Doll2=FAL
Doll3=ERROR
Doll4=ERROR
WeaponType=AssaultRifle
Enhancement=0
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
WorldSwitcher=5_4_friendly
LastXS=1125
LastYS=804

[GPU]
AMD=0
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0
#combatsims can be of values 1,2, or 3

CombatSimsData=0

LastXS=860
LastYS=775

**Describe the bug**
When running expedition only mode at start up it goes to ExpeditionArrive and gets stuck

**Screenshots**
![image](https://user-images.githubusercontent.com/41549935/57423002-03576300-71c7-11e9-9823-64357f72145b.png)

**Comment by EchoControl** [comment]
Hm, this part works with pixel colors. I'll work on fixing it tomorrow

**Comment by EchoControl** [comment]
Expedition mode is now rewritten and functions as intended.
