### ISSUE TITLE
autobattle stuck

### ISSUE THREAD

**Issue by alconium-labs** [EchoControl/Gunkolle#11]
**Desktop:**
What graphics card are you using?
gtx1050
**Config File:**
Post your Config File
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=5000
MinRandomWaitS=1000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=M4SOPMODII
Doll2=HK416
Doll3=ERROR
Doll4=ERROR
WeaponType=AssaultRifle
Enhancement=1
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
AutoBattleResend=1
WorldSwitcher=4_3E
LastXS=1070
LastYS=41
[GPU]
AMD=0
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0

#combatsims can be of values 1,2, or 3
CombatSimsData=1

LastXS=860
LastYS=775

**Describe the bug**
it stuck if autobattle drop tdoll
i think it should insert click untill found autobattleresend

**Screenshots**
Add screenshots with your android player and where the script has stopped.
![캡처2](https://user-images.githubusercontent.com/14901999/60955045-04c61880-a33b-11e9-8e18-c013b524a3c5.PNG)

**Comment by EchoControl** [comment]
Thanks, now I recall that made this only skip equipment. Will update it this week

**Comment by alconium-labs** [comment]
thx
