### ISSUE TITLE
Questions before forking

### ISSUE THREAD

**Issue by Ryahn** [EchoControl/Gunkolle#14]
I have read you have stopped playing GF. I just had a few questions for you.

1) /pics/DollList where do you get the images from? I am thinking it might be a wiki or sorts?
2) Have you testing it out using BlueStacks or others? If not, its fine. I thought I ask. 
3) Did you just run this outside of a VM (virtual machine) or in one?

I hope to hear back and thank you in advance if you do.

**Comment by EchoControl** [comment]
Hi, glad that someone will pick this script up and keep it alive!

1. I get images by directly making screenshots from emulator screen. This can be done manually via any screenshot tool (make sure no compression is applied) or via AHK itself. If line of AHK is missing some picture it will popup a window with build-in tool. Second solution is very useful when calibrating some maps, as it usually stops on some tricky parts. Also, it's sometimes better to make some parts of screenshot as small as possible for example nodes. 

2. No. It was only run and tested on NOX.

3. Never used script under VM. I might guess it could be buggy on VM, but not sure. 

If you will have any more questions or some help/assistance don't be shy and contact me by any means you seem fit. I would love to keep this script alive, but don't have any inspiration anymore. :)

**Comment by Ryahn** [comment]
Sorry for the late reply. Work has me busy during the day.

Alright cool. I thought that is how it was done for the pics but I wasnt sure. But it also good to know not to compress the images. 

Last question, would you like me to do pull request to this or just keep it on my own?

**Comment by EchoControl** [comment]
I guess pull request will be the best option.
