### ISSUE TITLE
Only works on OpenGL (compatibility) mode, invalid screen on DirectX (Speed) mode

### ISSUE THREAD

**Issue by Archeonyx** [EchoControl/Gunkolle#3]
**Desktop:**
What graphics card are you using?
GPU: Asus GTX 1050 Ti 4GB
CPU: Ryzen 5 2600X @4.15GHz
RAM: 16GB
Nox version: 6.1.0.0
Nox core count: 1 or 2 Core
Nox RAM: 3GB

Commit number:  f688790

**Describe the bug**
When using the DirectX mode, 100% of the time invalid screen always pops out, but works perfectly fine on OpenGL (compatibility) mode (flawlessly, to be clear).

I think using DirectX has differing pixel color codes.

**Comment by EchoControl** [comment]
It works on my machine, but yeah, it may differ I guess. There's part in readme regarding this.

![image](https://user-images.githubusercontent.com/49132081/57865926-25746500-7807-11e9-965d-3ef5a92d67da.png)
