### ISSUE TITLE
stuck in expedition arrive

### ISSUE THREAD

**Issue by alconium-labs** [EchoControl/Gunkolle#5]
**Desktop:**
What graphics card are you using?
gtx 1050
**Config File:**
Post your Config File

[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=5000
MinRandomWaitS=1000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=9A91
Doll2=M4SOPMODII
Doll3=ERROR
Doll4=ERROR
WeaponType=AssaultRifle
Enhancement=0
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
WorldSwitcher=4_3E
LastXS=762
LastYS=93
[GPU]
AMD=0
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0

#combatsims can be of values 1,2, or 3
CombatSimsData=0

LastXS=860
LastYS=775

**Describe the bug**

stuck in ExpeditionArrive File Not Found

**Screenshots**
Add screenshots with your android player and where the script has stopped.
https://imgur.com/RE9w3ii

**Comment by alconium-labs** [comment]
it seems work when i change Gunkolle/Constants/PixelColor.ahk 
 HPC := 0xDA9C09 ;Home
 ECHELONCLICK := 0xFFB600
 ChapterScreen := 0x21304A
 EmergencyClick := 0x311810
 ExpeditionReceived1 := 0xc6cb39
 ExpeditionReceived2 := 0x94a229

to

 HPC := 0xDA9C09 ;Home
 ECHELONCLICK := 0xFFB600
 ChapterScreen := 0x21304A
 EmergencyClick := 0x311810
 ExpeditionReceived1 := 0x211800
 ExpeditionReceived2 := 0x100C00

**Comment by EchoControl** [comment]
I'll check it today, thanks for input in advance.

**Comment by EchoControl** [comment]
Yeah, seems I forgot to change them back to original vars.
