### ISSUE TITLE
Issue with the script doing battles

### ISSUE THREAD

**Issue by KamKoi** [EchoControl/Gunkolle#6]
**Desktop:**
RX Vega 64 (AMD)

**Config File:**
[Do Not Modify]
Busy=0
[Variables]
SortieInterval=1000
MaxRandomWaitS=3000
MinRandomWaitS=3000
MinRandomWait=0
MaxRandomWait=0
WINID=ahk_class Qt5QWindowIcon
PauseHr=9
PauseMn=00
ResumeHr=12
ResumemN=00
Doll1=FAL
Doll2=G41
WeaponType=AssaultRifle
Enhancement=0
ProductionTdoll=0
ProductionEquipment=0
FriendCollector=0
BatteryCollector=0
AutoBattleResend=0
WorldSwitcher=5_4
LastXS=0
LastYS=0
[GPU]
AMD=1
#For AMD or others GPU's change value 0 to 1. For NVidia value must be 0

#combatsims can be of values 1,2, or 3
CombatSimsData=2

LastXS=0
LastYS=0

**Describe the bug**
Starting the script will do the initial steps fine (Will swap out dolls in formations, click and start the map) However as soon as the map starts it will either get hung up on the waiting for map state or will get hung up on clicking the heliport or command post. Attempted on different maps with varying zoom levels with the same problem persisting. Also have swapped graphics rendering mode to speed and compatible

**Screenshots**
https://i.imgur.com/8PTB53H.jpg

**Comment by EchoControl** [comment]
I wasn't been able to check this on amd side, as for now I don't have their gpu's. You just need to change some pics in /pics/maps/3_6 . If you can contact me, we can fix this issue together.

**Comment by KamKoi** [comment]
I found out creating my own pictures work and it's a slow process. Do exact resolutions matter? And should I be using a specific capture tool to make the pictures? I'm just using shareX and having images directly save onto my PC and renaming and replacing them.

Edit: Could you also provide references on what some of the pictures are looking for as well? If that's possible. So I could just make my own collection of images.

**Comment by EchoControl** [comment]
I personally use GreenShot cuz it's got magnification tool and doesn't compress the image. You need res of the pic to be the same as on the screen. Simply zoom out the map, and make a pics needed. For AMD, as I experienced, menu images works from nvidia gpus and vice versa (can't be exactly sure, gpu used was r9 380x). References you can find in this repo in /pics/. Exact reference of picture varies of the map and how it will be ran. 

UPD: You can just delete pics that doesn't work, and window will popup with image creation tool. It's not always works as should but makes work much easier. Also you can select the part of the capture which will be saved.

**Comment by KamKoi** [comment]
Making new images works well so far and it even sometimes recognizes the originals but there's another issue where after deploying the echelons it will trigger the event of clicking on either the heliport or command center, however it does this too fast and tries to click it during the "BATTLE START" overlay so it basically gets stuck in "Waiting for CommandCenterAfterClicked" which is an issue because it never clicked it in the first place. Otherwise manually clicking it will set it off and it will do everything else just fine.

**Comment by EchoControl** [comment]
Which map it is?

**Comment by KamKoi** [comment]
Currently, it does it on any map. It will get hung up on WaitingForXSelection because I assume it spots the image right before the BATTLE START message and it blocks it and thinks it has selected it when it hasn't. 

EDIT: after doing some trial and error I have managed to get it to work fully on 3-6 by playing around with how it's looking for the initial selection of the heliport. I'm guessing it was just a magical pixel thing. Will attempt same thing on other maps

**Comment by EchoControl** [comment]
You can look at Maps.ahk to see the logic of how map runs. WaitingFor is for `TFindClick `. For example, `HeliportResupply `and `HeliportResupply2 `is for clicking `HeliportResupply ` until `HeliportResupply2` is found. In case of 3_6 map it work as, it clicks node until it selected (finding that there are yellow line on the needed selected node). And after it found that node is selected (or `HeliportResupply2` is found) it goes to next step.

**Comment by KamKoi** [comment]
Yeah that makes sense. However what's odd is on 3_6 it places the corpse drag squad on the helipoint and then the second AR on the command post, but it resupplies the entire corpse drag squad and not the single second AR on the command post. what's up with that?

**Comment by EchoControl** [comment]
Yeah, I made it so, because boss runs aren't that good for corpse drags cuz girls will take a ton of damage and there isn't that powerful tank to effectively run it. I ran it with corpsedrag off, fyi

**Comment by KamKoi** [comment]
Ah I see, My squad was actually managing to kill the boss about 5 times before my main tanks needed actual repairs which I am fine with since I have a massive stockpile of quick repairs.

**Comment by EchoControl** [comment]
It's matters of how far are you in the game, so safest variant was to make it like this. I may add check mark for boss runs either user want or not to drag it.

Also, can you share your pics for AMD version so I can make it work on AMD?

**Comment by KamKoi** [comment]
Yeah sure, when I mess about with the pics more to make sure they're all rock solid I'll message you and send you the links for them.

**Comment by EchoControl** [comment]
Thanks! If you have some questions or can't understand what is where etc, feel free to ask it here or DM me in discord/telegram. It's in my bio.

**Comment by KamKoi** [comment]
I'm regarding this as fixed. It's just about me creating map specific pics. It's odd how it does the formation and doll swapping just fine but as soon as it enters a map it flips out. I guess that's the power of AMD.

Oh, and you should find a way to have it select only a specific Tdoll when it does the formation swapping. It sometimes places my dupe level 1 G41 instead of my level 100 g41.

**Comment by EchoControl** [comment]
It flips out on map, mostly due to effects on it, like fog and other stuff. 
Thing with dupes is kinda hard atm , as it searches just for their art not lvl or something else. Not sure if I will be able to fix it.

**Comment by KamKoi** [comment]
Ah yeah, I guess for specific T-dolls you should advise people to make a custom picture of the portrait. I just tested this and it works
